name: Test

on:
  pull_request:
    branches: 
      - develop

jobs:
  main:
    name: Test Scripts

    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: brew tap mgatner/pkg

      - name: Run Test Suite
        run: tests/run.sh
